# Generated by Django 5.1.3 on 2025-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadasa_spa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='clients',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
