# Generated by Django 5.2 on 2025-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadasa_spa', '0002_delete_about_remove_booking_service_booking_clients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='available_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('time_open', models.TimeField()),
                ('time_closed', models.TimeField()),
                ('current_status', models.CharField(choices=[('o', 'open'), ('x', 'closed')], default='o', max_length=20)),
            ],
        ),
    ]
