# Generated by Django 5.2 on 2025-05-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadasa_spa', '0003_available_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_time',
            name='current_status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=20),
        ),
    ]
