# Generated by Django 5.2 on 2025-05-06 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadasa_spa', '0004_alter_available_time_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='clientcomment',
            name='approved',
        ),
        migrations.AddField(
            model_name='clientcomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='clientcomment',
            name='reply',
            field=models.TextField(default='okay thanks'),
        ),
    ]
