# Generated by Django 5.2 on 2025-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadasa_spa', '0005_notification_remove_clientcomment_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcomment',
            name='reply',
            field=models.TextField(default='Thanks for the reply'),
        ),
    ]
